import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}

export const metadata = {
  title: "Hug Museum",
  description: "A live digital hug wall for sharing photos, videos, and stories of hugs.",
  openGraph: {
    title: "Hug Museum",
    description: "A live digital hug wall for sharing photos, videos, and stories of hugs.",
    url: "https://hugmuseum.vercel.app/",
    siteName: "Hug Museum",
    images: [
      {
        url: "https://hugmuseum.vercel.app/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "Hug Museum preview image",
      },
    ],
    locale: "en_GB",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Hug Museum",
    description: "A live digital hug wall for sharing photos, videos, and stories of hugs.",
    images: ["https://hugmuseum.vercel.app/og-image.jpg"],
  },
};
